### ISSUE TITLE
Nested lists rendering in the configuration form

### ISSUE THREAD

**Issue by mudrd8mz** [andrewhancox/block_databasetags#1]
I am experiencing weird issue with rendering those nested lists in the block config form. Looks like some CSS fixes needed there:

![screenshot_2015-11-13_09-48-27](https://cloud.githubusercontent.com/assets/85831/11142230/0b0af844-89ec-11e5-813b-63e0326a670e.png)

Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by mudrd8mz** [comment]
Looks a bit better in Chrome

**Comment by andrewhancox** [comment]
Fixed
