### ISSUE TITLE
Does not respect availability of the course / database module

### ISSUE THREAD

**Issue by mudrd8mz** [andrewhancox/block_databasetags#2]
The block config form simply exposes all fields of the type 'linkedcheckbox', 'checkbox' or 'tag' from all courses on the site. When configured, the block then shows the tags. Even if the user does not have access to the target course.

Reproduce:
1. Have some courses with databases with checkbox fields
2. As a student, put the block instance to their Dashboard page
3. When configuring the block, the student has access to all the fields, even without being enrolled into the course

This seems to be a serious bug to me, as some sensitive data could simply leak out (imagine teachers-only courses, personal courses etc where databases are used).

Additionally, on bigger sites with many databases, the config form will simply become too long.

Simple solution might be to allow the block be created in the course only (via `applicable_formats()` format). And then, the SQL that actually fetches the tags and the config form to be fixed so they check the actual availability of the target database.

**Comment by jb-fol** [comment]
That was a feature for the particular site it was designed for. It was originally designed in the way you describe.

For the commission, it was desirable to have the block list fields from any database in the site. Worst case scenario (for the commission) was block would show tags in a course that a user may not be enrolled in, but that wouldn't be a major problem as the user would be asked to enrol (or told that they could not enrol).

Thanks
Jon

Jon Bolton
http://twitter.com/jonbolton

**Comment by andrewhancox** [comment]
David, I agree that this needs dealing with and I'll be looking at it in the next week or two.
As Jon said, this was a conscious compromise to get this block built quickly and for a specific use case.

**Comment by andrewhancox** [comment]
Done
